@SET CONTENT_ROOT=%cd%;
@SET EXECUTION_ROOT=%cd%\src
@SET SOURCE_ROOT=%EXECUTION_ROOT%;

@CALL venv\Scripts\activate.bat

@SET PYTHONPATH=%CONTENT_ROOT%%SOURCE_ROOT%%PYTHONPATH%

@CD %EXECUTION_ROOT%
